### ISSUE TITLE
scene.py giving very low fps

### ISSUE THREAD

**Issue by jundaz** [erizmr/SPH_Taichi#2]
the provided demo runs in a very low fps, around 0.75-0.85 fps.
I tried both cpu and gpu, also tried disabling the saving frames but still very slow.
also tried disabling output sim_info

**Comment by erizmr** [comment]
Sorry for late reply. The reason for low fps is that the result is visualized per 50 simulation steps.  Now it has been change to be visualized every step, achieving 40 fps using cpu backend on my laptop

BTW, the code has been updated to be compatible with Taichi latest version v0.8.3.
