### ISSUE TITLE
Taichi version

### ISSUE THREAD

**Issue by ChiZhangatTUM** [erizmr/SPH_Taichi#21]
Hi, thanks for sharing your interesting work. 
I have tried to run your code, while failed due to the restricted taichi version installed by PIP. 
Should I build the taichi from source other than with pip installation?
Thanks

**Comment by erizmr** [comment]
Hi, there is no need to build from Taichi for this repo. Taichi >= 1.2.0 installed by PIP should work. BTW, which version of Taichi are you using? And it will be helpful if you can share some info about the failure? Thanks.

**Comment by ChiZhangatTUM** [comment]
Hi 
I have installed taichi through pip install --upgrade taichi with taichi 1.4.0 installed. 
And the print error is the following by running the dragon_bath simulation:

  warnings.warn(
Traceback (most recent call last):
  File "run_simulation.py", line 36, in <module>
    window = ti.ui.Window('SPH', (1024, 1024), show_window = True, vsync=False)
  File "/home/chi/.local/lib/python3.8/site-packages/taichi/ui/window.py", line 36, in __init__
    check_ggui_availability()
  File "/home/chi/.local/lib/python3.8/site-packages/taichi/ui/utils.py", line 85, in check_ggui_availability
    raise GGUINotAvailableException(
taichi.ui.utils.GGUINotAvailableException: GGUI is not available since you have installed a restricted version of taichi. Please see yellow warning messages printed during startup for details.

thanks

**Comment by erizmr** [comment]
Hi, thanks for providing this. The GGUI supports x64 / CUDA / Vulkan backends. Would you mind provide more info about your OS/ GPU or CPU?

**Comment by ChiZhangatTUM** [comment]
Hi 
My OS
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal

GPU and CUDA
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 520.61.05    Driver Version: 520.61.05    CUDA Version: 11.8     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA RTX A5000    On   | 00000000:01:00.0 Off |                  Off |
| 30%   30C    P8    16W / 230W |    216MiB / 24564MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+

Vulkan

==========
VULKANINFO
==========

Vulkan Instance Version: 1.2.131


Thanks for your help

**Comment by erizmr** [comment]
Thanks for providing this. Have tried to upgrade PIP and re-install?

**Comment by ChiZhangatTUM** [comment]
> Thanks for providing this. Have you tried to upgrade PIP and re-install?

Tried while failed with the same error. 
Looks like this error is related with the Linux OS, I will try with another computer. 
Best

**Comment by erizmr** [comment]
Hi, I asked Taichi developers about this issue. It seems that `pip >= 20.3, python 3.8.10+, 3.9.5+, 3.10.0+` is required.

**Comment by ChiZhangatTUM** [comment]
> Hi, I asked Taichi developers about this issue and got reply that `pip >= 20.3, python 3.8.10+, 3.9.5+, 3.10.0+` is required for GGUI.

Thanks, I have upgrade the pip to pip 22.3.1, now taichi works with the default installation.

**Comment by ChiZhangatTUM** [comment]
I close this issue. Thanks a lot.

**Comment by ChiZhangatTUM** [comment]
I close this issue. Thanks a lot.
