### ISSUE TITLE
GPU跑不了是为啥？

### ISSUE THREAD

**Issue by chunleili** [erizmr/SPH_Taichi#4]
CPU算的太慢了，不知道为啥改成GPU就跑不了了。是因为代码里用了什么东西吗？

**Comment by erizmr** [comment]
应该是Taichi pre-allocated的 1G memory不够了
有两种解决方案：
1. 多分配一些显存，```ti.init(arch=ti.gpu, device_memory_GB=1.5)```
2. 用packed mode，```ti.init(arch=ti.gpu, packed=True)```，但packed mode可能会影响一些性能
